LOGGING = False

# HAL server PORTS
HAL_REST_PORT = 10505
HAL_WS_PORT = 10005

# HAL URL paths
HAL_BASE_URL_PATH = '/hal'

# HAL REST HTTP Response status codes
NOT_FOUND_HTTP_RESPONSE_CODE = 404
ERROR_HTTP_RESPONSE_CODE = 500
OK_HTTP_RESPONSE_CODE = 200

# HAL WS common OPCODEs
HAL_WS_OPEN_CONNECTION_OPCODE = 3
HAL_WS_CONNECTION_OPENED_OPCODE = 4
HAL_WS_SEND_DATA_OPCODE = 5
HAL_WS_GOT_DATA_OPCODE = 6
# HAL WS closing frame status code
HAL_WS_CLOSE_FRAME_STATUS_NORMAL = 1000
HAL_WS_CLOSE_FRAME_STATUS_EXCEPTION = 4000

# HAL URL paths for USB-to-Serial
HAL_USB_TO_SERIAL_BASE_PATH = HAL_BASE_URL_PATH + '/rs232'
HAL_USB_TO_SERIAL_GET_LIST_PATH = HAL_USB_TO_SERIAL_BASE_PATH + '/list'
# HAL USB-to-Serial config property names
HAL_USB_TO_SERIAL_PORT_PROPERTY_NAME = 'port'
HAL_USB_TO_SERIAL_BAUDRATE_PROPERTY_NAME = 'baudrate'
HAL_USB_TO_SERIAL_BYTESIZE_PROPERTY_NAME = 'bytesize'
HAL_USB_TO_SERIAL_PARITY_PROPERTY_NAME = 'parity'
HAL_USB_TO_SERIAL_STOPBITS_PROPERTY_NAME = 'stopbits'
HAL_USB_TO_SERIAL_TIMEOUT_PROPERTY_NAME = 'timeout'
HAL_USB_TO_SERIAL_XONXOFF_PROPERTY_NAME = 'xonxoff'
HAL_USB_TO_SERIAL_RTSCTS_PROPERTY_NAME = 'rtscts'
HAL_USB_TO_SERIAL_DSRDTR_PROPERTY_NAME = 'dsrdtr'
HAL_USB_TO_SERIAL_WRITE_TIMEOUT_PROPERTY_NAME = 'write_timeout'
HAL_USB_TO_SERIAL_INTER_BYTE_TIMEOUT_PROPERTY_NAME = 'inter_byte_timeout'

# copy from WebSocketServerProtocol
STATE_CLOSED = 0
STATE_CONNECTING = 1
STATE_CLOSING = 2
STATE_OPEN = 3
STATE_PROXY_CONNECTING = 4
ws_states = {STATE_CLOSED: 'CLOSED', STATE_CONNECTING: 'CONNECTING', STATE_CLOSING: 'CLOSING', STATE_OPEN: 'OPEN',
             STATE_PROXY_CONNECTING: 'PROXY CONNECTING'}

# HWC cmd names commands
LSCPU = 'lscpu'
LSPCI = 'lspci'
LSHW = 'lshw'
LSUSB = 'lsusb'
PROC = '/proc/{}'
CPU_INFO = 'cpuinfo'

# HWC full commands to run
LSCPU_CMD = [LSCPU]
LSPCI_CMD = [LSPCI, '-nnmm']
LSHW_CMD = [LSHW, '-json']
LSUSB_CMD = [LSUSB]
CPU_INFO_CMD = ['cat', PROC.format(CPU_INFO)]

# HI REST URL paths
HAL_HWC_BASE_URL = HAL_BASE_URL_PATH + '/hwc'
HAL_HWC_GET_LSCPU_INFO_PATH = HAL_HWC_BASE_URL + '/' + LSCPU
HAL_HWC_GET_LSCPU_INFO_PATH = HAL_HWC_BASE_URL + '/' + LSCPU
HAL_HWC_GET_CPU_INFO_PATH = HAL_HWC_BASE_URL + PROC.format(CPU_INFO)
HAL_HWC_GET_LSPCI_INFO_PATH = HAL_HWC_BASE_URL + '/' + LSPCI
HAL_HWC_GET_LSHW_INFO_PATH = HAL_HWC_BASE_URL + '/' + LSHW
HAL_HWC_GET_LSUSB_INFO_PATH = HAL_HWC_BASE_URL + '/' + LSUSB

# LSUSB property names
HAL_LSUSB_BUS_NUMBER_PROPERTY_NAME = 'bus_number'
HAL_LSUSB_DEVICE_NUMBER_PROPERTY_NAME = 'device_bus_number'
HAL_LSUSB_MANUFACTURE_ID_PROPERTY_NAME = 'manufacture_id'
HAL_LSUSB_DEVICE_ID_PROPERTY_NAME = 'device_id'
HAL_LSUSB_MANUFACTURE_AND_DEVICE_NAME_PROPERTY_NAME = 'manufacture_device_name'

# LSPCI property names
HAL_LSPCI_BUS_NUMBER_PROPERTY_NAME = 'bus_number'
HAL_LSPCI_DEVICE_NUMBER_PROPERTY_NAME = 'bus_device_number'
HAL_LSPCI_FUNCTION_NUMBER_PROPERTY_NAME = 'bus_function_number'
HAL_LSPCI_REVISION_NUMBER_PROPERTY_NAME = 'revision_number'
HAL_LSPCI_DEVICE_CLASS_PROPERTY_NAME = 'device_class'
HAL_LSPCI_DEVICE_CLASS_ID_PROPERTY_NAME = 'device_class_id'
HAL_LSPCI_DEVICE_ID_PROPERTY_NAME = 'device_id'
HAL_LSPCI_DEVICE_VENDOR_ID_PROPERTY_NAME = 'device_vendor_id'
HAL_LSPCI_DEVICE_VENDOR_PROPERTY_NAME = 'device_vendor'
HAL_LSPCI_DEVICE_NAME_PROPERTY_NAME = 'device_name'
